# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tibalt/linux-summer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tibalt/linux-summer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tibalt/linux-summer/CMakeFiles /home/tibalt/linux-summer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tibalt/linux-summer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named road

# Build rule for target.
road: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 road
.PHONY : road

# fast build rule for target.
road/fast:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/build
.PHONY : road/fast

bold.o: bold.cpp.o

.PHONY : bold.o

# target to build an object file
bold.cpp.o:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/bold.cpp.o
.PHONY : bold.cpp.o

bold.i: bold.cpp.i

.PHONY : bold.i

# target to preprocess a source file
bold.cpp.i:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/bold.cpp.i
.PHONY : bold.cpp.i

bold.s: bold.cpp.s

.PHONY : bold.s

# target to generate assembly for a file
bold.cpp.s:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/bold.cpp.s
.PHONY : bold.cpp.s

cautious.o: cautious.cpp.o

.PHONY : cautious.o

# target to build an object file
cautious.cpp.o:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/cautious.cpp.o
.PHONY : cautious.cpp.o

cautious.i: cautious.cpp.i

.PHONY : cautious.i

# target to preprocess a source file
cautious.cpp.i:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/cautious.cpp.i
.PHONY : cautious.cpp.i

cautious.s: cautious.cpp.s

.PHONY : cautious.s

# target to generate assembly for a file
cautious.cpp.s:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/cautious.cpp.s
.PHONY : cautious.cpp.s

road.o: road.cpp.o

.PHONY : road.o

# target to build an object file
road.cpp.o:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/road.cpp.o
.PHONY : road.cpp.o

road.i: road.cpp.i

.PHONY : road.i

# target to preprocess a source file
road.cpp.i:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/road.cpp.i
.PHONY : road.cpp.i

road.s: road.cpp.s

.PHONY : road.s

# target to generate assembly for a file
road.cpp.s:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/road.cpp.s
.PHONY : road.cpp.s

simulation.o: simulation.cpp.o

.PHONY : simulation.o

# target to build an object file
simulation.cpp.o:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/simulation.cpp.o
.PHONY : simulation.cpp.o

simulation.i: simulation.cpp.i

.PHONY : simulation.i

# target to preprocess a source file
simulation.cpp.i:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/simulation.cpp.i
.PHONY : simulation.cpp.i

simulation.s: simulation.cpp.s

.PHONY : simulation.s

# target to generate assembly for a file
simulation.cpp.s:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/simulation.cpp.s
.PHONY : simulation.cpp.s

van.o: van.cpp.o

.PHONY : van.o

# target to build an object file
van.cpp.o:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/van.cpp.o
.PHONY : van.cpp.o

van.i: van.cpp.i

.PHONY : van.i

# target to preprocess a source file
van.cpp.i:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/van.cpp.i
.PHONY : van.cpp.i

van.s: van.cpp.s

.PHONY : van.s

# target to generate assembly for a file
van.cpp.s:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/van.cpp.s
.PHONY : van.cpp.s

vehicle.o: vehicle.cpp.o

.PHONY : vehicle.o

# target to build an object file
vehicle.cpp.o:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/vehicle.cpp.o
.PHONY : vehicle.cpp.o

vehicle.i: vehicle.cpp.i

.PHONY : vehicle.i

# target to preprocess a source file
vehicle.cpp.i:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/vehicle.cpp.i
.PHONY : vehicle.cpp.i

vehicle.s: vehicle.cpp.s

.PHONY : vehicle.s

# target to generate assembly for a file
vehicle.cpp.s:
	$(MAKE) -f CMakeFiles/road.dir/build.make CMakeFiles/road.dir/vehicle.cpp.s
.PHONY : vehicle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... road"
	@echo "... bold.o"
	@echo "... bold.i"
	@echo "... bold.s"
	@echo "... cautious.o"
	@echo "... cautious.i"
	@echo "... cautious.s"
	@echo "... road.o"
	@echo "... road.i"
	@echo "... road.s"
	@echo "... simulation.o"
	@echo "... simulation.i"
	@echo "... simulation.s"
	@echo "... van.o"
	@echo "... van.i"
	@echo "... van.s"
	@echo "... vehicle.o"
	@echo "... vehicle.i"
	@echo "... vehicle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

